model:
  type: object_detection
  backbone: resnet34
  layers: -2
  anchor: [[32, 64, 128, 256, 512]]
  aspect_ratio: [[1.0, 0.5, 2.0]]
  out_channels: 512
  num_classes: 21

train:
  epochs: 2
  batch_size: 2
  optimizer:
    name: SGD
    lr: 0.001
    momentum: 0.9
  lr_scheduler:
    name: StepLR
    step_size: 3
    gamma: 0.1

test:
  model: models/best_dec.pkl
  batch_size: 8

dataset:
  name: voc2017
  dataset_dir: data/pascal_voc2017
  label_mapping:
    aeroplane: 1
    bicycle: 2
    bird: 3
    boat: 4
    bottle: 5
    bus: 6
    car: 7
    cat: 8
    chair: 9
    cow: 10
    diningtable: 11
    dog: 12
    horse: 13
    motorbike: 14
    person: 15
    pottedplant: 16
    sheep: 17
    sofa: 18
    tvmonitor: 19
    train: 20

